name:         mammut-control
version:      0.9.0
synopsis:     Mammut control API and web site
category:     Backup
homepage:     https://www.mammutdata.com
author:       Thomas Feron <thomas.feron@redspline.com>
license-file: LICENSE

flags:
  devel:
    description: Compile the project for fast reloads
    manual: True
    default: False

ghc-options:
  - -Wall

dependencies:
  - base >=4.9 && <5
  - bcrypt
  - bytestring
  - mtl
  - servant-auth-server
  - servant-server >=0.12
  - text
  - time
  - transformers-base

default-extensions:
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeOperators

library:
  source-dirs: src

  when:
    - condition: flag(devel)
      exposed-modules:
        - MammutControl.DevelServer
      dependencies:
        - foreign-store
      ghc-options: -O0

  dependencies:
    - aeson
    - monad-control
    - opaleye
    - optparse-applicative
    - postgresql-simple
    - product-profunctors >=0.9
    - profunctors
    - resource-pool
    - resourcet
    - servant
    - servant-auth
    - unordered-containers
    - wai
    - warp
    - yaml

executables:
  mammut-control:
    source-dirs: .
    main:        Main.hs
    dependencies:
      - mammut-control

tests:
  unit-tests:
    source-dirs: tests
    main:        Suite.hs
    ghc-options: -threaded
    dependencies:
      - hedgehog
      - jose
      - mammut-control
      - tasty
      - tasty-hedgehog
